version: '3.8'
services:
  api:
    container_name: flaskcnr
    image: .
    depends_on:
    - database
    entrypoint: python app.py
    environment:
      REDIS_HOST: database
    ports:
    - '5000:5000'
  database:
    container_name: rediscnr
    image: redis
    ports:
    - '6379:6379'
    volumes:
    - dbdata:/data
volumes:
  dbdata:
  
