# please refer to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: bakerywork

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
      - name: helmtest
        run: helm install myapp helm
