# please refer to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: bakerywork

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenaorio tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment tfdo run testjs against'
        type: environment
        required: true

  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Create kind cluster
        id: setup-kind
        uses: helm/kind-action@v1.1.0
        with:
          config: cluster.yaml
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: cd $GITHUB_WORKSPACE
      - name: Set up Python 3.7
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ always() }}
        timeout-minutes: 30
        
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "tagname: $tagname"
          echo "headref: $GITHUB_HEAD_REF"
          echo "PR_${GITHUB_ACTOR}_${GITHUB_HEAD_REF}"
          python $GITHUB_WORKSPACE/app/main.py
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/app
        env:
          LEVEL: ${{ github.event.inputs.logLevel }}
          TAGS: ${{ github.event.inputs.tags }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          
          tagname: ${{ github.event.release.tag_name }}
      
     # - run: docker-compose up -d --build && sleep 10 && docker ps -a
     # - name: test compose
     #   run: docker run --network container:flaskcnr appropriate/curl -s http://localhost:5000/oven
#       - name: Set up Helm
#         uses: azure/setup-helm@v1
#         with:
#           version: v3.8.1

#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.7
#       - name: Create kind cluster
#         uses: helm/kind-action@v1.2.0
#       - name: helmtest
#         run: |
#           cd $GITHUB_WORKSPACE
#           helm install myapp helm
