# please refer to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: bakerywork

on:
  push:
    branches: [ workflowtest ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker compose
        run: cd $GITHUB_WORKSPACE
      - run: docker-compose up -d
      - name: test compose
        run: |
          sleep 5
          docker run --network container:flaskcnr -i busybox curl -s --retry 10 --retry-connrefused http://localhost:5000/
#         - uses: shogo82148/actions-setup-redis@v1
#           with:      
#             redis-version: '6.x'
#         - run: redis-cli ping
#         - run: docker build -t ct .
#         - run: docker run --env REDIS_HOST='localhost' --name ff --detach ct
#         - run: |    
#             sleep 5
#             docker run --network container:ff appropriate/curl -s  --retry 10 --retry-connrefused http://localhost:5000/oven
#        - uses: KengoTODA/actions-setup-docker-compose@main
 #         with:
  #           version: '1.29.2' 
#       - name: Set up Helm
#         uses: azure/setup-helm@v1
#         with:
#           version: v3.8.1

#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.7
#       - name: Create kind cluster
#         uses: helm/kind-action@v1.2.0
#       - name: helmtest
#         run: |
#           cd $GITHUB_WORKSPACE
#           helm install myapp helm
